language: php

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  include:
    - php: 7.1
      env: dependencies=lowest
      dist: precise
    - php: 7.3
      env: dependencies=highest
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - if [ -z "$dependencies" ]; then travis_retry composer install --no-interaction; fi;
  - if [ "$dependencies" = "lowest" ]; then travis_retry composer update --prefer-lowest --no-interaction; fi;
  - if [ "$dependencies" = "highest" ]; then travis_retry composer update --no-interaction; fi;
  - composer show

script:
  - ./vendor/bin/phpunit -v --coverage-text --coverage-clover=./build/logs/clover.xml

after_success:
  - if [ -f ./build/logs/clover.xml ]; then wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.1.0/coveralls.phar; fi
  - if [ -f ./build/logs/clover.xml ]; then php ./coveralls.phar -v; fi
