language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

matrix:
  include:
    - php: 5.3
      env: dependencies=lowest
    - php: 7.2
      env: dependencies=highest
  fast_finish: true

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - if [ -z "$dependencies" ]; then travis_retry composer install --no-interaction; fi;
  - if [ "$dependencies" = "lowest" ]; then travis_retry composer update --prefer-lowest --no-interaction; fi;
  - if [ "$dependencies" = "highest" ]; then travis_retry composer update --no-interaction; fi;
  - composer show

script:
  - phpunit -v --coverage-text --coverage-clover=./build/logs/clover.xml

after_success:
  - if [ -f ./build/logs/clover.xml ]; then travis_retry composer require satooshi/php-coveralls --no-interaction --update-with-dependencies; fi
  - if [ -f ./build/logs/clover.xml ]; then php vendor/bin/coveralls -v; fi
